const STATUS = ["ACTIVE", "IN-ACTIVE"];
const SEAT_STATUS = { AVAILABLE: "AVAILABLE", BOOKED: "BOOKED", RESERVED: "RESERVED" };
const ROLE = ["ADMIN", "USER"];
const DEFAULT_SEAT_STATUS = "AVAILABLE";
const ACTIVE_STATUS = "ACTIVE";
const INACTIVE_STATUS = "IN-ACTIVE";
const DEFAULT_USER_ROLE = "USER";
const BOOKED = "BOOKED";
const RESERVED = "RESERVED";
const ADMIN = "ADMIN";
const USER = "USER";
const TOTAL_SEATS_CAPACITY = 100;
const BOOKING_STATUS = {
  PENDING: "PENDING",
  BOOKED: "BOOKED",
  VISITED: "VISITED",
  CANCEL: 'CANCEL',
  RESERVED: 'RESERVED'
};
module.exports = {
  STATUS,
  SEAT_STATUS,
  DEFAULT_SEAT_STATUS,
  ACTIVE_STATUS,
  INACTIVE_STATUS,
  DEFAULT_USER_ROLE,
  BOOKED,
  TOTAL_SEATS_CAPACITY,
  RESERVED,
  ADMIN,
  USER,
  ROLE,
  BOOKING_STATUS
};
